version: "3.5"

services:
  api01: &api
    image: rinha-backend-2024-q1-api
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=admin
      - DB_PASSWORD=123
      - DB_DATABASE=rinha
      - DB_PORT=5432
      - API_PORT=3000
    depends_on:
      - db
    deploy:
      # replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: '150MB'

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=admin
      - DB_PASSWORD=123
      - DB_DATABASE=rinha
      - DB_PORT=5432
      - API_PORT=3000
  
  nginx:
    image: nginx:latest
    ports:
    - "9999:9999"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'

  db:
    image: postgres:alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "200MB"